/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GitWorkflowRouteImport } from './routes/git-workflow'
import { Route as IndexRouteImport } from './routes/index'

const GitWorkflowRoute = GitWorkflowRouteImport.update({
  id: '/git-workflow',
  path: '/git-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/git-workflow': typeof GitWorkflowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/git-workflow': typeof GitWorkflowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/git-workflow': typeof GitWorkflowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/git-workflow'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/git-workflow'
  id: '__root__' | '/' | '/git-workflow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GitWorkflowRoute: typeof GitWorkflowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/git-workflow': {
      id: '/git-workflow'
      path: '/git-workflow'
      fullPath: '/git-workflow'
      preLoaderRoute: typeof GitWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GitWorkflowRoute: GitWorkflowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
